W=(...w)=>I(4,_=>m[h]+=(x>>w[i]&1)*3<<i*2)|++h
m[P]=K
J(2,U,_=>m[G+j+i*T]=z++)
m[D]=1
F(r,b=>W(4,5,6,7,x=b)|W(0,1,2,3))
F(l,b=>J(2,2,_=>W(a=6-4*i,a,++a,a,x=b)|W(a-=3,a,++a,a)))
dt=c=0
m[V]=_=>dt++
m[H]=_=>(m[X]=Math.sin(m[LY]*dt))
m[H]=(y,h)=>{c=Math.sin(2*m[LY]/144+dt/20)*40-40;m[SCX]=(m[LY]%2?c:c);m[SCY]=c}